### ISSUE TITLE
Display value on hover

### ISSUE THREAD

**Issue by Dopaz** [johannesMatevosyan/starwarsjs#8]
I'm trying to display the star value in a custom div on hover.

<div id="valore"></div>

I added a function in starwars.js in the hover section but the syntax should not be right.

                $(this).hover( // change star's color after mouse hover
                    function () {
                    star_id = $(this).attr('data-value');
			$(this).find('#valore').html(star_id);
		    },

Thank you for the nice script and for your help

**Comment by johannesMatevosyan** [comment]
Hi,
Sorry for the late reply. I guess you tried to put #valore inside the selector therefore it did not work, because it is against the concepts of this plugin, since all code is generetaed inside the selector.
Instead you could locate you div somewhere around and assign `data` attribute value to it. Hope my description is clear.
        
`
 HTML code :

		<div class="rate_row"></div>

		<div id="valore"></div>

JS code :

             $('.rate_row > span').hover(function () {
	                      star_id = $(this).attr('data-value'); 
	                     $(this).parent().siblings('#valore').html(star_id);
                     }
             );      
`	

 Thanks for intereseting idea!
